language: c

compiler: gcc

before_install:

install:
  - wget http://downloads.sourceforge.net/libxls/libxls-0.2.0.tar.gz
  - tar -xzvf libxls-0.2.0.tar.gz
  - cd libxls-0.2.0
  - ./configure --prefix=$HOME
  - make
  - make install

before_script:
  - export LD_LIBRARY_PATH="$HOME/lib":$LD_LIBRARY_PATH

script:
  - cd ../src
  - gcc -o xls2csv *.c -I$HOME/include -L/$HOME/lib -lxlsreader
